apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: fuse-app
  namespace: pipelines
spec:
  params:
    - default: camel-rest-sample
      name: APP_NAME
      type: string
    - default: 'https://github.com/sahilsethi12/Camel-Rest-Sample.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/app-sit/camel-rest-sample
      name: IMAGE_NAME
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: subdirectory
          value: $(params.APP_NAME)
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: local-maven-repo
    - name: maven-build
      params:
        - name: subdirectory
          value: $(params.APP_NAME)
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven-build
      workspaces:
        - name: output
          workspace: local-maven-repo
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: $(params.APP_NAME)
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
      runAfter:
        - maven-build
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: local-maven-repo
    - name: my-skopeo-copy
      params:
        - name: srcImageURL
          value: $(params.IMAGE_NAME)
        - name: destImageURL
          value: >-
            example-registry-quay-quay-registry.apps.cluster-n2gmg.n2gmg.sandbox1085.opentlc.com/admin/$(params.APP_NAME)
        - name: srcTLSverify
          value: 'true'
        - name: destTLSverify
          value: 'false'
        - name: quay-secret
          value: quay-pull-secret
        - name: CONTEXT
          value: $(params.APP_NAME)
      runAfter:
        - buildah
      taskRef:
        kind: Task
        name: my-skopeo-copy
      workspaces:
        - name: source
          workspace: local-maven-repo
    - name: scan-image
      params:
        - name: imageName
          value: demo
        - name: quay-secret
          value: quay-pull-secret
      runAfter:
        - my-skopeo-copy
      taskRef:
        kind: Task
        name: scan-image
      workspaces:
        - name: source
          workspace: local-maven-repo
  workspaces:
    - name: local-maven-repo
