resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesJson6902:
- patch: |-
    - op: add
      path: /metadata/labels/testkey1
      value: testvalue1
  target:
    group: apps
    kind: Deployment
    name: camel-rest-sample
    version: v1
images:
- name: sample
  newTag: 0234c71
